services:
  wildfly:
    container_name: mini-cringe
    hostname: localhost
    image: quay.io/wildfly/wildfly:28.0.0.Final-jdk17
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Djboss.bind.address=0.0.0.0 -Dorg.wildfly.ee.namespace.interop=true
    volumes:
      - ./build/libs/lab-2-1.war:/opt/jboss/wildfly/standalone/deployments/app.war
    extra_hosts:
      - "lil-star:192.168.31.233"

  postgres:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pswrd
    ports:
      - "5432:5432"
